name: IntelliJ Plugin Compatibility

on:
  # Trigger the workflow on pushes to only the 'main' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [ main ]

  # Trigger the workflow on any pull request
  pull_request:

  # Trigger the workflow on a schedule; daily
  schedule:
    - cron: '0 0 * * *'

jobs:
  compatibility:
    name: Ensure plugin compatibility against targeted platform version & the latest EAP snapshot for both IDEA Community, IDEA Ultimate.

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: gradle

      - name: Build the plugin
        run: ./gradlew buildPlugin

      - name: Generate IDE Versions List
        run: ./gradlew generateIdeVersionsList

      - name: Verify plugin on IntelliJ Platforms
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
        with:
          # Generated from the `generateIdeVersionsList` task above.
          ide-versions: build/intellij-platform-plugin-verifier-action-ide-versions-file.txt

      - name: Get log file path and print contents
        run: |
          echo "The log file path is: ${{steps.verify.outputs.verification-output-log-filename}}" ;
          cat ${{steps.verify.outputs.verification-output-log-filename}}
