name: IntelliJ Plugin Compatibility

on:
  # Trigger the workflow on pushes to only the 'master' branch (this avoids duplicate checks being run e.g. for dependabot pull requests)
  push:
    branches: [ master ]

  # Trigger the workflow on any pull request
  pull_request:

  # Trigger the workflow on a schedule; daily
  schedule:
    - cron: '0 0 * * *'

jobs:
  compatibility:
    name: Ensure plugin compatibility against targeted platform version & the latest EAP snapshot for both IDEA Community, IDEA Ultimate.

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.4.0

      - name: Setup Java 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Build the plugin
        run: ./gradlew buildPlugin

      - name: Verify plugin on IntelliJ Platforms
        id: verify
        uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
        with:
          ide-versions: |
            ideaIC:2021.3
            ideaIU:2021.3
            ideaIC:LATEST-EAP-SNAPSHOT
            ideaIU:LATEST-EAP-SNAPSHOT

      - name: Get log file path and print contents
        run: |
          echo "The log file path is: ${{steps.verify.outputs.verification-output-log-filename}}" ;
          cat ${{steps.verify.outputs.verification-output-log-filename}}
