# Taken on 2025-08-30 from: https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#general-usage
name: 'Dependency Submission & Review'

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: write

jobs:
  dependency-submission-and-review:
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        timeout-minutes: 1

      # Setup Java
      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        timeout-minutes: 5
        with:
          distribution: zulu
          java-version: 21

      # Generate and submit dependency graph
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2
        with:
          # Reducing storage costs for saved dependency graph artifacts (store for 1 day instead of 30 days)
          # See: https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#reducing-storage-costs-for-saved-dependency-graph-artifacts
          artifact-retention-days: 1 # Default is 30 days or as configured for repository

          # Publishing a Develocity Build ScanÂ® from your dependency submission workflow
          # Why: A Build Scan makes it easy to determine the source of any dependency vulnerabilities in your project.
          # See: https://github.com/gradle/actions/blob/main/docs/dependency-submission.md#publishing-a-develocity-build-scan-from-your-dependency-submission-workflow
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/help/legal-terms-of-use"
          build-scan-terms-of-use-agree: "yes"

      # Dependency Review (on PR only)
      - name: Dependency Review
        if: github.event_name == 'pull_request'
        uses: actions/dependency-review-action@05fe4576374b728f0c523d6a13d64c25081e0803 # v4.8.3