name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:


jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        timeout-minutes: 1

      - name: Setup Java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        timeout-minutes: 5
        with:
          distribution: zulu
          java-version: 21
          cache: gradle

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@512b1875f3b6270828abfe77b247d5895a2da1e5 # v2.1.0
        with:
          repo-token: ${{ secrets.GH_PAT_REPO_SCOPE_FOR_ACTIONS_THAT_OPEN_PRS }}
          merge-method: SQUASH
          # NOTE: Can not set reviewer to self (`ChrisCarini`) because using PAT for self.
          #  From Docs:
          #     Note that if you're using a Personal Access Token (PAT) as repo-token you cannot 
          #     request a review from the user that the PAT belongs to.
          #  Ref: https://github.com/gradle-update/update-gradle-wrapper-action#reviewers
#          reviewers: |
#            ChrisCarini