name: 'Update JetBrains Plugin Platform Version'

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  update-jetbrains-plugin-platform-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN_FOR_IJ_UPDATE_ACTION }}

      - uses: ChrisCarini/gh-test-ij-release-update-action@main
        with:
          PAT_TOKEN_FOR_IJ_UPDATE_ACTION: ${{ secrets.PAT_TOKEN_FOR_IJ_UPDATE_ACTION }}
